const NZ = "Pacific/Auckland";
const CN = "Asia/Shanghai";

function nzOffset(date: string) {
  return date >= "2026-09-27" ? "+13:00" : "+12:00";
}

function iso(date: string, time: string, zone: "nz" | "cn") {
  const offset = zone === "cn" ? "+08:00" : nzOffset(date);
  return `${date}T${time}:00${offset}`;
}

function event(
  input: Record<string, unknown> & {
    title: string;
    kind: "flight" | "drive" | "stay" | "explore" | "transfer";
    start: string;
    end: string;
    timezone: string;
  },
) {
  return {
    subtitle: "",
    certainty: "suggested" as const,
    place: "",
    address: "",
    phone: "",
    source: "行程表",
    note: "",
    documents: [] as string[],
    from: "",
    to: "",
    code: "",
    timeMode: "timed" as const,
    timeRange: false,
    endUnspecified: false,
    ...input,
  };
}

function stay(input: {
  title: string;
  checkIn: string;
  checkOut: string;
  place: string;
  address: string;
  phone: string;
  note: string;
}) {
  return event({
    title: input.title,
    kind: "stay",
    certainty: "confirmed",
    timezone: NZ,
    timeRange: true,
    start: iso(input.checkIn, "15:00", "nz"),
    end: iso(input.checkOut, "10:00", "nz"),
    place: input.place,
    address: input.address,
    phone: input.phone,
    note: input.note,
  });
}

export const tripMeta = {
  title: "2026 南北岛自驾",
  start_date: "2026-09-24",
  end_date: "2026-10-09",
  timezone: NZ,
  home_timezone: CN,
  currency: "NZD" as const,
  home_currency: "CNY" as const,
  destinations: [
    { name: "奥克兰 · 新西兰", timezone: NZ, currency: "NZD" as const },
    { name: "Parapara", timezone: NZ, currency: "NZD" as const },
    { name: "Lake Tekapo", timezone: NZ, currency: "NZD" as const },
    { name: "Lake Hawea", timezone: NZ, currency: "NZD" as const },
    { name: "Te Anau", timezone: NZ, currency: "NZD" as const },
    { name: "皇后镇 · 新西兰", timezone: NZ, currency: "NZD" as const },
  ],
};

export function itineraryEvents() {
  return [
    event({
      title: "上海 ✈️ 奥克兰",
      kind: "flight",
      certainty: "confirmed",
      timezone: CN,
      endTimezone: NZ,
      start: iso("2026-09-24", "14:15", "cn"),
      end: iso("2026-09-25", "05:40", "nz"),
      from: "上海浦东 T2",
      to: "Auckland",
      code: "NZ288",
      note: "Air NZ NZ288。浦东 T2 出发，抵达时刻以值机屏为准。",
    }),
    event({
      title: "入境与提车",
      kind: "transfer",
      timezone: NZ,
      start: iso("2026-09-25", "05:40", "nz"),
      end: iso("2026-09-25", "09:00", "nz"),
      place: "Auckland Airport",
      note: "海关、检疫与租车。约 3 小时，步行与接驳。",
    }),
    event({
      title: "Mission Bay",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-25", "12:30", "nz"),
      end: iso("2026-09-25", "14:30", "nz"),
      place: "Mission Bay",
      note: "海滨散步，车程短。",
    }),
    event({
      title: "Mt Eden",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-25", "16:00", "nz"),
      end: iso("2026-09-25", "18:30", "nz"),
      place: "Mt Eden",
      note: "入住后再去。车停山下步行登顶。留意环岛让行。",
    }),
    stay({
      title: "奥克兰住宿",
      checkIn: "2026-09-25",
      checkOut: "2026-09-27",
      place: "Auckland",
      address: "90A Edgewater Drive, Auckland 2010",
      phone: "+64 21 130 7748",
      note: "Last-Minute Deal · 3BR Family Stay，两晚。15:00 后入住，27 日 10:00 前退房。",
    }),
    event({
      title: "南下 Matamata",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-26", "08:00", "nz"),
      end: iso("2026-09-26", "10:00", "nz"),
      from: "Auckland",
      to: "Matamata",
      note: "SH1 南下约 2 小时。Hobbiton 场次 10:40。",
    }),
    event({
      title: "Hobbiton",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-26", "10:40", "nz"),
      end: iso("2026-09-26", "13:30", "nz"),
      place: "Hobbiton",
      note: "官方导览约 2–3 小时。阵雨天仍开放。",
    }),
    event({
      title: "Blue Spring",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-26", "14:00", "nz"),
      end: iso("2026-09-26", "16:30", "nz"),
      place: "Blue Spring",
      note: "Te Waihou Walkway，Leslie Road 入口，平缓步行。",
    }),
    event({
      title: "返回奥克兰",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-26", "16:30", "nz"),
      end: iso("2026-09-26", "18:30", "nz"),
      from: "Blue Spring",
      to: "Auckland",
      note: "避开 SH1 晚高峰。当晚仍住 Edgewater Drive。",
    }),
    event({
      title: "奥克兰还车",
      kind: "transfer",
      timezone: NZ,
      start: iso("2026-09-27", "08:00", "nz"),
      end: iso("2026-09-27", "09:30", "nz"),
      place: "Auckland Airport",
      note: "国内航班 NZ5067 10:45。预留还车与安检。",
    }),
    event({
      title: "奥克兰 ✈️ Nelson",
      kind: "flight",
      certainty: "confirmed",
      timezone: NZ,
      start: iso("2026-09-27", "10:45", "nz"),
      end: iso("2026-09-27", "12:20", "nz"),
      from: "Auckland",
      to: "Nelson",
      code: "NZ5067",
      note: "Air NZ NZ5067。雨天按延误准备，不必按取消改票。",
    }),
    event({
      title: "Nelson 提车与补给",
      kind: "transfer",
      timezone: NZ,
      start: iso("2026-09-27", "12:20", "nz"),
      end: iso("2026-09-27", "14:20", "nz"),
      place: "Nelson",
      note: "机场提车后可在 Richmond 超市采购两到三天物资。",
    }),
    event({
      title: "前往 Parapara",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-27", "14:20", "nz"),
      end: iso("2026-09-27", "16:30", "nz"),
      from: "Nelson",
      to: "Parapara",
      note: "经 Motueka、SH60。当晚住 Golden Bay Beach Retreat，不是 Motueka。",
    }),
    stay({
      title: "Parapara 住宿",
      checkIn: "2026-09-27",
      checkOut: "2026-09-28",
      place: "Parapara",
      address: "99 Tukurua Road, Parapara, Tasman 7182",
      phone: "+64 3 525 9742",
      note: "Golden Bay Beach Retreat · Private Deck & Sea Views。只住 27 日一晚。15:00 后入住，28 日 10:00 前退房。",
    }),
    event({
      title: "前往 Wharariki",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-28", "08:30", "nz"),
      end: iso("2026-09-28", "11:00", "nz"),
      from: "Parapara",
      to: "Wharariki Beach",
      note: "从 Parapara 出发，不是从 Motueka。翻 Takaka Hill 路段已在前一天下午。",
    }),
    event({
      title: "Wharariki Beach",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-28", "11:00", "nz"),
      end: iso("2026-09-28", "16:30", "nz"),
      place: "Wharariki Beach",
      note: "下午低潮约 17:23（Whanganui Inlet，大潮、退得很干净）。15:30–18:00 最适合沙滩；若要赶路去 Gowanbridge，需在天黑前离开。",
    }),
    event({
      title: "前往 Gowanbridge",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-28", "16:30", "nz"),
      end: iso("2026-09-28", "20:30", "nz"),
      from: "Wharariki Beach",
      to: "Gowanbridge",
      note: "经 Motueka 转入 SH6，往 Murchison 方向。9 月底日落约 19:30，后半段可能天黑，注意负鼠。当晚住 Gowanbridge B&B，不是 Parapara 第二晚。",
    }),
    stay({
      title: "Gowanbridge 住宿",
      checkIn: "2026-09-28",
      checkOut: "2026-09-29",
      place: "Gowanbridge",
      address: "2 Gowan Valley Road R.D. 3, Gowanbridge, Tasman 7077",
      phone: "+64 3 523 9816",
      note: "Gowanbridge B&B · Farm Stay · Nelson Lakes。28 日一晚。15:00 后入住，29 日 10:00 前退房。",
    }),
    event({
      title: "Lewis Pass",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-29", "08:00", "nz"),
      end: iso("2026-09-29", "10:00", "nz"),
      from: "Gowanbridge",
      to: "Lewis Pass",
      note: "经 Murchison 上 SH7。三人轮换。",
    }),
    event({
      title: "前往 Geraldine",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-29", "10:00", "nz"),
      end: iso("2026-09-29", "14:00", "nz"),
      from: "Lewis Pass",
      to: "Geraldine",
      note: "可在 Springs Junction 或 Culverden 换驾休息。",
    }),
    event({
      title: "前往 Lake Tekapo",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-09-29", "14:00", "nz"),
      end: iso("2026-09-29", "16:00", "nz"),
      from: "Geraldine",
      to: "Lake Tekapo",
      note: "可停 Fairlie Bakehouse。入住 Connemara Retreat。",
    }),
    stay({
      title: "Lake Tekapo 住宿",
      checkIn: "2026-09-29",
      checkOut: "2026-10-01",
      place: "Lake Tekapo",
      address: "3 Dwyer Place, Lake Tekapo, Canterbury 7999",
      phone: "+64 22 368 0600",
      note: "Connemara Retreat。29、30 日两晚。15:00 后入住，10 月 1 日 10:00 前退房。",
    }),
    event({
      title: "Church of the Good Shepherd",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-30", "09:00", "nz"),
      end: iso("2026-09-30", "10:00", "nz"),
      place: "Lake Tekapo",
    }),
    event({
      title: "Mt John Observatory",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-30", "10:30", "nz"),
      end: iso("2026-09-30", "12:30", "nz"),
      place: "Mt John",
      note: "可开车到观景台。",
    }),
    event({
      title: "Lake Tekapo 自由活动",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-09-30", "13:00", "nz"),
      end: iso("2026-09-30", "18:00", "nz"),
      place: "Lake Tekapo",
      note: "湖边散步。无长途驾驶。",
    }),
    event({
      title: "前往 Mt Cook",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-01", "07:00", "nz"),
      end: iso("2026-10-01", "08:45", "nz"),
      from: "Lake Tekapo",
      to: "Mt Cook",
      note: "08:45 前到机场办理冰川飞行。",
    }),
    event({
      title: "冰川观光飞行",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-01", "09:30", "nz"),
      end: iso("2026-10-01", "11:30", "nz"),
      place: "Mt Cook Airport",
      note: "低云或西风湿时可能取消，下午改 Hooker Valley。",
    }),
    event({
      title: "Hooker Valley Track",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-01", "12:30", "nz"),
      end: iso("2026-10-01", "15:30", "nz"),
      place: "Hooker Valley",
      note: "往返约 10 km 平缓栈道。",
    }),
    event({
      title: "前往 Twizel",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-01", "16:00", "nz"),
      end: iso("2026-10-01", "17:00", "nz"),
      from: "Mt Cook",
      to: "Twizel",
    }),
    event({
      title: "Twizel 观星",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-01", "20:00", "nz"),
      end: iso("2026-10-01", "22:30", "nz"),
      place: "Twizel",
      note: "Aoraki Mackenzie 暗夜保护区。云量看当晚雷达和卫星。",
    }),
    stay({
      title: "Twizel 住宿",
      checkIn: "2026-10-01",
      checkOut: "2026-10-02",
      place: "Twizel",
      address: "204 MacKenzie Drive, Twizel, Canterbury 7901",
      phone: "+64 3 435 0655",
      note: "Twizel Getaway。1 日一晚。15:00 后入住，2 日 10:00 前退房。",
    }),
    event({
      title: "前往 Lake Ōhau",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-02", "09:00", "nz"),
      end: iso("2026-10-02", "09:30", "nz"),
      from: "Twizel",
      to: "Lake Ōhau",
    }),
    event({
      title: "Lake Ōhau",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-02", "09:30", "nz"),
      end: iso("2026-10-02", "11:30", "nz"),
      place: "Lake Ōhau",
      note: "湖边停留，不必爬山。",
    }),
    event({
      title: "前往 Lake Hawea",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-02", "12:00", "nz"),
      end: iso("2026-10-02", "14:00", "nz"),
      from: "Lake Ōhau",
      to: "Lake Hawea",
      note: "经 Lindis Pass。",
    }),
    event({
      title: "Lake Hawea",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-02", "14:00", "nz"),
      end: iso("2026-10-02", "17:00", "nz"),
      place: "Lake Hawea",
    }),
    stay({
      title: "Lake Hawea 住宿",
      checkIn: "2026-10-02",
      checkOut: "2026-10-04",
      place: "Lake Hawea",
      address: "212 Lakeview Terrace, Lake Hawea, Otago 9382",
      phone: "+64 27 526 6545",
      note: "Lakeview Haven Apartment。2、3 日两晚。15:00 后入住，4 日 10:00 前退房。",
    }),
    event({
      title: "前往 Wanaka",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-03", "07:00", "nz"),
      end: iso("2026-10-03", "08:00", "nz"),
      from: "Lake Hawea",
      to: "Wanaka",
    }),
    event({
      title: "Isthmus Peak Track",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-03", "08:00", "nz"),
      end: iso("2026-10-03", "16:00", "nz"),
      place: "Isthmus Peak",
      note: "日间徒步约 8 小时。Roy's Peak 产羔期关闭。可改较短路线。",
    }),
    event({
      title: "返回 Lake Hawea",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-03", "16:00", "nz"),
      end: iso("2026-10-03", "17:00", "nz"),
      from: "Wanaka",
      to: "Lake Hawea",
    }),
    event({
      title: "前往 Cromwell",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-04", "09:00", "nz"),
      end: iso("2026-10-04", "11:30", "nz"),
      from: "Lake Hawea",
      to: "Cromwell",
      note: "可在 Jones Family Fruit Stall 休息。",
    }),
    event({
      title: "前往 Te Anau",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-04", "12:00", "nz"),
      end: iso("2026-10-04", "15:00", "nz"),
      from: "Cromwell",
      to: "Te Anau",
    }),
    event({
      title: "Te Anau 湖畔与 Kepler",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-04", "15:30", "nz"),
      end: iso("2026-10-04", "17:30", "nz"),
      place: "Te Anau",
      note: "湖畔散步；Kepler 只走入口附近，不是全线。采购次日干粮。",
    }),
    stay({
      title: "Te Anau 住宿",
      checkIn: "2026-10-04",
      checkOut: "2026-10-06",
      place: "Te Anau",
      address: "6 Harrison Court, Te Anau, Southland 9600",
      phone: "+64 21 109 1883",
      note: "Te Anau Gardens Apartment 2。4、5 日两晚。15:00 后入住，6 日 10:00 前退房。",
    }),
    event({
      title: "前往 Milford Sound",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-05", "07:30", "nz"),
      end: iso("2026-10-05", "10:30", "nz"),
      from: "Te Anau",
      to: "Milford Sound",
      note: "SH94 无手机信号。出发前看 NZTA。沿途 Mirror Lakes、Homer Tunnel、The Chasm。",
    }),
    event({
      title: "Milford Sound 游船",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-05", "11:00", "nz"),
      end: iso("2026-10-05", "14:00", "nz"),
      place: "Milford Sound",
      note: "峡湾游船。雨天仍值得去；封路才换日。",
    }),
    event({
      title: "返回 Te Anau",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-05", "14:30", "nz"),
      end: iso("2026-10-05", "17:30", "nz"),
      from: "Milford Sound",
      to: "Te Anau",
    }),
    event({
      title: "前往皇后镇",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-06", "09:00", "nz"),
      end: iso("2026-10-06", "11:30", "nz"),
      from: "Te Anau",
      to: "Queenstown",
      note: "经 Devil's Staircase。",
    }),
    event({
      title: "Queenstown Gardens 与 Steamer Wharf",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-06", "13:00", "nz"),
      end: iso("2026-10-06", "15:00", "nz"),
      place: "Queenstown",
    }),
    event({
      title: "Skyline Gondola",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-06", "15:00", "nz"),
      end: iso("2026-10-06", "18:00", "nz"),
      place: "Queenstown",
    }),
    stay({
      title: "皇后镇住宿",
      checkIn: "2026-10-06",
      checkOut: "2026-10-08",
      place: "Queenstown",
      address: "35B Wynyard Crescent, Queenstown 9300",
      phone: "+64 22 105 0422",
      note: "Best View in Queenstown, Modern & Stylish House。6、7 日两晚。15:00 后入住，8 日 10:00 前退房。",
    }),
    event({
      title: "前往 Glenorchy",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-07", "09:00", "nz"),
      end: iso("2026-10-07", "10:00", "nz"),
      from: "Queenstown",
      to: "Glenorchy",
    }),
    event({
      title: "Lagoon Walkway",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-07", "10:00", "nz"),
      end: iso("2026-10-07", "12:00", "nz"),
      place: "Glenorchy",
    }),
    event({
      title: "前往 Arrowtown",
      kind: "drive",
      timezone: NZ,
      start: iso("2026-10-07", "13:00", "nz"),
      end: iso("2026-10-07", "14:00", "nz"),
      from: "Glenorchy",
      to: "Arrowtown",
    }),
    event({
      title: "Arrowtown",
      kind: "explore",
      timezone: NZ,
      start: iso("2026-10-07", "14:00", "nz"),
      end: iso("2026-10-07", "17:00", "nz"),
      place: "Arrowtown",
      note: "自由游玩。当晚决定次日是否需要更早去机场。",
    }),
    event({
      title: "休整与还车",
      kind: "transfer",
      timezone: NZ,
      start: iso("2026-10-08", "09:00", "nz"),
      end: iso("2026-10-08", "12:00", "nz"),
      place: "Queenstown",
      note: "10:00 前退房。伴手礼、还车。国内航班 NZ618 18:00。",
    }),
    event({
      title: "皇后镇 ✈️ 奥克兰",
      kind: "flight",
      certainty: "confirmed",
      timezone: NZ,
      start: iso("2026-10-08", "18:00", "nz"),
      end: iso("2026-10-08", "19:50", "nz"),
      from: "Queenstown",
      to: "Auckland",
      code: "NZ618",
      note: "Air NZ NZ618。与国际段非联程，延误按 奥克兰 过夜准备。",
    }),
    event({
      title: "奥克兰 ✈️ 上海",
      kind: "flight",
      certainty: "confirmed",
      timezone: NZ,
      endTimezone: CN,
      start: iso("2026-10-08", "23:45", "nz"),
      end: iso("2026-10-09", "06:55", "cn"),
      from: "Auckland",
      to: "上海浦东 T2",
      code: "NZ289",
      note: "Air NZ NZ289。国内到达与国际起飞空档约 4 小时。",
    }),
  ];
}

export const packingList = [
  ["证件", "护照与签证页", "随身携带，不要上传到行程网站"],
  ["证件", "国际驾照及翻译", ""],
  ["装备", "转换插头", ""],
  ["装备", "防风层与雨壳", "Golden Bay 和峡湾都会刮风"],
  ["行前", "下载南岛 Google 离线地图", "SH94 无信号"],
  ["行前", "确认租车", "9.25 奥克兰取、9.27 奥克兰还；Nelson 再取、皇后镇 10.8 还"],
  ["行前", "安装 MetService 与 Windy", "用雷达看雨区移动，不要只看太阳图标"],
];
